## **Retail Market Basket Analysis using Apriori Algorithm.**

#### *Project Overview.

##### - In this project, I analyzed **grocery store transaction data** to identify which products are frequently purchased together.
##### (This analysis helps businesses improve their **cross-selling strategies**.)

#### *Objective.

##### - Identify customer purchase patterns.
##### - Discover product associations.
##### - Provide cross-selling recommendations for business growth.

### 1. Libraries Import.**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder
import warnings
warnings.filterwarnings('ignore')

### 2. Loading Dataset.**

In [2]:
df = pd.read_csv('Data/OnlineRetail.csv', encoding='latin1')

In [3]:
df.shape

(541909, 8)

In [4]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [6]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

### 3. Data Cleaning.**

#### (1). Finding Missing Values.

In [7]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

#### (2). Fixing Missing Values.

In [8]:
# Drop rows where CustomerID is null.
df.dropna(subset=['CustomerID'], inplace=True)

# Drop rows where Description is null.
df.dropna(subset=['Description'], inplace=True)

In [9]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [10]:
df.shape

(406829, 8)

#### (3). Removing Duplicate Rows.

In [11]:
# Check how many duplicates are there.

df.duplicated().sum()

np.int64(5225)

In [12]:
# Remove duplicate rows.

df.drop_duplicates(inplace=True)

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.shape

(401604, 8)

#### (4). Fixing Data Types.

In [15]:
# Check current data types.
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [16]:
# Convert InvoiceDate from object to datetime.
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [17]:
# Convert CustomerID from float to int to string.
df['CustomerID'] = df['CustomerID'].astype(int).astype(str)

In [18]:
# Convert InvoiceNo to string.
df['InvoiceNo'] = df['InvoiceNo'].astype(str)

In [19]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID             object
Country                object
dtype: object

#### (5). Fixing Inconsistent Data.

In [20]:
# Convert Description to uppercase and strip spaces.
df['Description'] = df['Description'].str.upper().str.strip()

In [21]:
# Strip spaces from Country
df['Country'] = df['Country'].str.strip()

In [22]:
# Check the first character distribution of InvoiceNo (to identify cancellations).
df['InvoiceNo'].str[0].value_counts()

InvoiceNo
5    392732
C      8872
Name: count, dtype: int64

In [23]:
# Cancelled orders remove.
df = df[~df['InvoiceNo'].str.startswith('C')]

In [24]:
df['InvoiceNo'].str[0].value_counts()

InvoiceNo
5    392732
Name: count, dtype: int64

In [25]:
# Remove negative quantity rows.
df = df[df['Quantity'] > 0]

In [26]:
# Remove zero and negative price rows.
df = df[df['UnitPrice'] > 0]

In [27]:
df.shape

(392692, 8)

#### (6). Finding & Fixing Outliers using IQR Method.

##### Quantity.

In [28]:
df['Quantity'].max()

np.int64(80995)

In [29]:
df['Quantity'].min()

np.int64(1)

##### UnitPrice.

In [30]:
df['UnitPrice'].max()

np.float64(8142.75)

In [31]:
df['UnitPrice'].min()

np.float64(0.001)

In [32]:
# IQR for Quantity

Q1_qty = df['Quantity'].quantile(0.25)
Q3_qty = df['Quantity'].quantile(0.75)

IQR_qty = Q3_qty - Q1_qty

lower_qty = Q1_qty - 1.5 * IQR_qty
upper_qty = Q3_qty + 1.5 * IQR_qty

In [33]:
# IQR for UnitPrice.

Q1_price = df['UnitPrice'].quantile(0.25)
Q3_price = df['UnitPrice'].quantile(0.75)

IQR_price = Q3_price - Q1_price

lower_price = Q1_price - 1.5 * IQR_price
upper_price = Q3_price + 1.5 * IQR_price

In [34]:
# Remove outliers.

df = df[(df['Quantity'] >= lower_qty) & (df['Quantity'] <= upper_qty)]
df = df[(df['UnitPrice'] >= lower_price) & (df['UnitPrice'] <= upper_price)]

In [35]:
# Outliers Fixed using IQR!.

df['Quantity'].max()

np.int64(27)

In [36]:
df['UnitPrice'].max()

np.float64(7.5)

#### (7). Removing Single Item Transactions.

In [37]:
# Count items per invoice.
invoice_counts = df.groupby('InvoiceNo')['Description'].count()

In [38]:
len(invoice_counts)

16826

In [39]:
# Keep only invoices with 2 or more items.
valid_invoices = invoice_counts[invoice_counts >= 2].index

In [40]:
df = df[df['InvoiceNo'].isin(valid_invoices)]

In [41]:
# Single Item Transactions Removed.
df['InvoiceNo'].nunique()

15725

In [42]:
df.shape

(332133, 8)

#### (8). Filtering UK Data Only.

In [43]:
df['Country'].value_counts().head()

Country
United Kingdom    299274
Germany             7423
France              6879
EIRE                5428
Spain               2035
Name: count, dtype: int64

In [44]:
# Keep only United Kingdom data
df = df[df['Country'] == 'United Kingdom']

In [45]:
df.shape

(299274, 8)

#### (9). Removing Invalid Products.

In [46]:
# Remove non-product entries
invalid = ['POSTAGE', 'DOTCOM POSTAGE', 'MANUAL',
           'BANK CHARGES', 'AMAZONFEE', 'TEST']

df = df[~df['Description'].isin(invalid)]

In [47]:
df.shape

(299105, 8)

#### (10). Cleaning Column Names.

In [48]:
# Convert column names to lowercase
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [49]:
df.columns.tolist()

['invoiceno',
 'stockcode',
 'description',
 'quantity',
 'invoicedate',
 'unitprice',
 'customerid',
 'country']

In [50]:
df.shape

(299105, 8)

#### Saving Cleaned Data.

In [51]:
# Save cleaned data to CSV
df.to_csv('Data/CleanedRetail.csv', index=False)

#### Saving Cleaned Data to PostgreSQL.

In [52]:
from sqlalchemy import create_engine

In [53]:
host="localhost",
user="postgres",
password="Pinku@2003#",
database="retail_db",
port=5432

In [54]:
# Connect to PostgreSQL.

engine = create_engine('postgresql+psycopg2://postgres:Pinku%402003%23@localhost:5432/retail_db')

In [55]:
# Save data to PostgreSQL

table_name = 'retail_data'
df.to_sql(
    table_name,
    engine,
    if_exists='replace',
    index=False,
    chunksize=10000,
    method='multi'
)

299105